// frontend/src/views/BacktestResults.vue
<template>
  <div class="backtest-results-container">
    <h1>回测结果</h1>
    
    <div class="backtest-layout">
      <!-- 左侧：回测任务列表 -->
      <div class="backtest-list">
        <div class="panel">
          <div class="panel-header">
            <h2>回测任务</h2>
            <button class="btn btn-primary btn-sm">新建回测</button>
          </div>
          <div class="panel-body">
            <div 
              v-for="task in backtestTasks" 
              :key="task.id"
              :class="['backtest-task-item', { active: selectedTaskId === task.id }]"
              @click="selectTask(task.id)"
            >
              <div class="task-header">
                <div class="task-name">{{ task.name }}</div>
                <div :class="['task-status', task.status]">{{ task.status }}</div>
              </div>
              <div class="task-meta">
                <div class="task-date">{{ task.date }}</div>
                <div class="task-return">{{ task.return }}%</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- 右侧：回测结果详情 -->
      <div class="backtest-detail">
        <!-- 回测概览 -->
        <div class="panel">
          <div class="panel-header">
            <h2>回测概览</h2>
          </div>
          <div class="panel-body">
            <div class="overview-grid">
              <div class="metric-card">
                <div class="metric-label">总收益率</div>
                <div class="metric-value positive">12.56%</div>
              </div>
              <div class="metric-card">
                <div class="metric-label">年化收益率</div>
                <div class="metric-value positive">8.32%</div>
              </div>
              <div class="metric-card">
                <div class="metric-label">最大回撤</div>
                <div class="metric-value negative">-4.21%</div>
              </div>
              <div class="metric-card">
                <div class="metric-label">夏普比率</div>
                <div class="metric-value">1.85</div>
              </div>
              <div class="metric-card">
                <div class="metric-label">胜率</div>
                <div class="metric-value">62.3%</div>
              </div>
              <div class="metric-card">
                <div class="metric-label">交易次数</div>
                <div class="metric-value">156</div>
              </div>
            </div>
          </div>
        </div>
        
        <!-- 绩效分析 -->
        <div class="panel">
          <div class="panel-header">
            <h2>绩效分析</h2>
          </div>
          <div class="panel-body">
            <div class="chart-container">
              <div ref="returnChartRef" class="chart"></div>
            </div>
          </div>
        </div>
        
        <!-- 交易详情和风险分析 -->
        <div class="grid-layout">
          <!-- 交易详情 -->
          <div class="panel">
            <div class="panel-header">
              <h2>交易详情</h2>
            </div>
            <div class="panel-body">
              <div class="table-container">
                <table class="data-table">
                  <thead>
                    <tr>
                      <th>日期</th>
                      <th>标的</th>
                      <th>类型</th>
                      <th>价格</th>
                      <th>数量</th>
                      <th>收益</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="trade in trades" :key="trade.id">
                      <td>{{ trade.date }}</td>
                      <td>{{ trade.symbol }}</td>
                      <td>{{ trade.type }}</td>
                      <td>{{ trade.price }}</td>
                      <td>{{ trade.quantity }}</td>
                      <td :class="trade.profit >= 0 ? 'positive' : 'negative'">
                        {{ trade.profit >= 0 ? '+' : '' }}{{ trade.profit }}%
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          
          <!-- 风险分析 -->
          <div class="panel">
            <div class="panel-header">
              <h2>风险分析</h2>
            </div>
            <div class="panel-body">
              <div class="risk-metrics">
                <div class="risk-item">
                  <div class="risk-label">波动率</div>
                  <div class="risk-value">6.8%</div>
                </div>
                <div class="risk-item">
                  <div class="risk-label">索提诺比率</div>
                  <div class="risk-value">2.1</div>
                </div>
                <div class="risk-item">
                  <div class="risk-label">卡尔马比率</div>
                  <div class="risk-value">1.97</div>
                </div>
                <div class="risk-item">
                  <div class="risk-label">信息比率</div>
                  <div class="risk-value">0.75</div>
                </div>
              </div>
              <div class="chart-container small">
                <div ref="riskChartRef" class="chart"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import * as echarts from 'echarts'

// 回测任务数据
const backtestTasks = ref([
  { id: 1, name: '策略A回测', status: 'completed', date: '2024-01-15', return: 12.56 },
  { id: 2, name: '策略B回测', status: 'completed', date: '2024-01-14', return: -3.21 },
  { id: 3, name: '策略C回测', status: 'running', date: '2024-01-15', return: 0 },
  { id: 4, name: '策略A回测', status: 'completed', date: '2024-01-13', return: 5.67 },
  { id: 5, name: '策略B回测', status: 'completed', date: '2024-01-12', return: 8.92 },
])

// 选中的回测任务ID
const selectedTaskId = ref(1)

// 交易数据
const trades = ref([
  { id: 1, date: '2024-01-15', symbol: 'BTCUSDT', type: '买入', price: 42000, quantity: 0.01, profit: 2.5 },
  { id: 2, date: '2024-01-14', symbol: 'ETHUSDT', type: '卖出', price: 2300, quantity: 0.1, profit: -1.2 },
  { id: 3, date: '2024-01-13', symbol: 'BTCUSDT', type: '买入', price: 41500, quantity: 0.01, profit: 3.8 },
  { id: 4, date: '2024-01-12', symbol: 'ETHUSDT', type: '卖出', price: 2350, quantity: 0.1, profit: 2.1 },
  { id: 5, date: '2024-01-11', symbol: 'BTCUSDT', type: '买入', price: 41000, quantity: 0.01, profit: 1.5 },
])

// 图表引用
const returnChartRef = ref<HTMLElement | null>(null)
const riskChartRef = ref<HTMLElement | null>(null)
let returnChart: echarts.ECharts | null = null
let riskChart: echarts.ECharts | null = null

// 选择回测任务
const selectTask = (taskId: number) => {
  selectedTaskId.value = taskId
  // 这里可以添加加载回测结果的逻辑
}

// 初始化收益率曲线图表
const initReturnChart = () => {
  if (!returnChartRef.value) return
  
  returnChart = echarts.init(returnChartRef.value)
  
  const option = {
    title: {
      text: '收益率曲线',
      left: 'center',
      textStyle: {
        fontSize: 16,
        fontWeight: 'normal'
      }
    },
    tooltip: {
      trigger: 'axis',
      formatter: '{b}: {c}%'
    },
    xAxis: {
      type: 'category',
      data: ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12', '2024-01-13', '2024-01-14', '2024-01-15']
    },
    yAxis: {
      type: 'value',
      axisLabel: {
        formatter: '{value}%'
      }
    },
    series: [{
      data: [0, 1.2, 2.5, 1.8, 3.2, 4.5, 3.8, 5.2, 6.5, 5.8, 7.2, 8.5, 10.2, 9.8, 12.56],
      type: 'line',
      smooth: true,
      lineStyle: {
        color: '#4a6cf7'
      },
      areaStyle: {
        color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
          { offset: 0, color: 'rgba(74, 108, 247, 0.3)' },
          { offset: 1, color: 'rgba(74, 108, 247, 0.05)' }
        ])
      }
    }]
  }
  
  returnChart.setOption(option)
}

// 初始化风险分析图表
const initRiskChart = () => {
  if (!riskChartRef.value) return
  
  riskChart = echarts.init(riskChartRef.value)
  
  const option = {
    title: {
      text: '最大回撤',
      left: 'center',
      textStyle: {
        fontSize: 14,
        fontWeight: 'normal'
      }
    },
    tooltip: {
      trigger: 'axis',
      formatter: '{b}: {c}%'
    },
    xAxis: {
      type: 'category',
      data: ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15']
    },
    yAxis: {
      type: 'value',
      axisLabel: {
        formatter: '{value}%'
      }
    },
    series: [{
      data: [0, -2.1, -3.5, -4.21],
      type: 'bar',
      itemStyle: {
        color: '#f87272'
      }
    }]
  }
  
  riskChart.setOption(option)
}

// 监听窗口大小变化，调整图表大小
const handleResize = () => {
  returnChart?.resize()
  riskChart?.resize()
}

// 组件挂载时初始化图表
onMounted(() => {
  initReturnChart()
  initRiskChart()
  window.addEventListener('resize', handleResize)
})

// 组件卸载时销毁图表
onMounted(() => {
  return () => {
    window.removeEventListener('resize', handleResize)
    returnChart?.dispose()
    riskChart?.dispose()
  }
})
</script>

<style scoped>
.backtest-results-container {
  padding: 20px;
}

.backtest-layout {
  display: flex;
  gap: 20px;
  margin-top: 20px;
}

.backtest-list {
  width: 300px;
  flex-shrink: 0;
}

.backtest-detail {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.panel {
  background-color: #ffffff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  overflow: hidden;
}

.panel-header {
  padding: 16px 20px;
  border-bottom: 1px solid #e5e7eb;
  background-color: #f9fafb;
}

.panel-header h2 {
  font-size: 18px;
  font-weight: 600;
  margin: 0;
  color: #1f2937;
}

.panel-body {
  padding: 20px;
}

/* 回测任务列表 */
.backtest-task-item {
  padding: 16px;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  margin-bottom: 12px;
  cursor: pointer;
  transition: all 0.3s ease;
}

.backtest-task-item:hover {
  border-color: #4a6cf7;
  box-shadow: 0 2px 8px rgba(74, 108, 247, 0.1);
}

.backtest-task-item.active {
  border-color: #4a6cf7;
  background-color: #f0f4ff;
}

.task-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.task-name {
  font-weight: 500;
  color: #1f2937;
}

.task-status {
  padding: 4px 8px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: 500;
}

.task-status.completed {
  background-color: #d1fae5;
  color: #065f46;
}

.task-status.running {
  background-color: #dbeafe;
  color: #1e40af;
}

.task-status.failed {
  background-color: #fee2e2;
  color: #991b1b;
}

.task-meta {
  display: flex;
  justify-content: space-between;
  font-size: 12px;
  color: #6b7280;
}

.task-return {
  font-weight: 500;
  color: #10b981;
}

/* 概览网格 */
.overview-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 16px;
}

.metric-card {
  background-color: #f9fafb;
  padding: 16px;
  border-radius: 6px;
  text-align: center;
}

.metric-label {
  font-size: 12px;
  color: #6b7280;
  margin-bottom: 8px;
}

.metric-value {
  font-size: 24px;
  font-weight: 600;
  color: #1f2937;
}

.metric-value.positive {
  color: #10b981;
}

.metric-value.negative {
  color: #ef4444;
}

/* 图表容器 */
.chart-container {
  height: 300px;
  margin-top: 20px;
}

.chart-container.small {
  height: 200px;
}

.chart {
  width: 100%;
  height: 100%;
}

/* 网格布局 */
.grid-layout {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
}

/* 表格容器 */
.table-container {
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 14px;
}

.data-table th,
.data-table td {
  padding: 12px;
  text-align: left;
  border-bottom: 1px solid #e5e7eb;
}

.data-table th {
  background-color: #f9fafb;
  font-weight: 600;
  color: #1f2937;
}

.data-table td {
  color: #6b7280;
}

.data-table tr:hover {
  background-color: #f9fafb;
}

.positive {
  color: #10b981;
}

.negative {
  color: #ef4444;
}

/* 风险指标 */
.risk-metrics {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-bottom: 20px;
}

.risk-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px;
  background-color: #f9fafb;
  border-radius: 6px;
}

.risk-label {
  font-size: 14px;
  color: #6b7280;
}

.risk-value {
  font-size: 16px;
  font-weight: 600;
  color: #1f2937;
}

/* 按钮样式 */
.btn {
  padding: 8px 16px;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s ease;
}

.btn-primary {
  background-color: #4a6cf7;
  color: white;
}

.btn-primary:hover {
  background-color: #3b5bdb;
}

.btn-sm {
  padding: 6px 12px;
  font-size: 12px;
}

/* 响应式设计 */
@media (max-width: 1200px) {
  .backtest-layout {
    flex-direction: column;
  }
  
  .backtest-list {
    width: 100%;
  }
  
  .grid-layout {
    grid-template-columns: 1fr;
  }
}
</style>

// frontend/src/views/BacktestResults.tsx
/**
 * 回测结果页面组件
 * 功能：展示回测任务列表和详细的回测结果，包括概览、绩效分析、交易详情和风险分析
 */
import { useState, useEffect, useRef } from 'react';
import * as echarts from 'echarts';
import { backtestApi } from '../api';
import '../styles/BacktestResults.css';
import { useTranslation } from 'react-i18next';


// 回测任务类型定义
interface BacktestTask {
  id: string;
  strategy_name: string;
  created_at: string;
  status: string;
  total_return?: number;
  max_drawdown?: number;
}

// 交易记录类型定义
interface Trade {
  EntryTime: string;
  ExitTime: string;
  Duration: string;
  Direction: string;
  EntryPrice: number;
  ExitPrice: number;
  Size: number;
  PnL: number;
  ReturnPct: number;
  Tag?: string;
  ID?: string;
}

// 回测指标类型定义
interface MetricItem {
  name: string;
  value: any;
  cn_name: string;
  en_name: string;
  description: string;
}

// 回测结果类型定义
interface BacktestResult {
  task_id: string;
  status: string;
  message: string;
  strategy_name: string;
  backtest_config: any;
  metrics: MetricItem[];
  trades: Trade[];
  equity_curve: any[];
  strategy_data: any[];
}

const BacktestResults = () => {
  // 回测任务数据
  const [backtestTasks, setBacktestTasks] = useState<BacktestTask[]>([]);

  // 选中的回测任务ID
  const [selectedTaskId, setSelectedTaskId] = useState<string>('');

  // 回测结果详情
  const [backtestResult, setBacktestResult] = useState<BacktestResult | null>(null);

  // 国际化支持
  const { t } = useTranslation();

  // 交易数据
  const [trades, setTrades] = useState<Trade[]>([]);

  // 回测指标
  const [metrics, setMetrics] = useState<MetricItem[]>([]);

  // 加载状态
  const [loading, setLoading] = useState<boolean>(false);

  // 图表引用
  const returnChartRef = useRef<HTMLDivElement>(null);
  const riskChartRef = useRef<HTMLDivElement>(null);
  const returnChart = useRef<echarts.ECharts | null>(null);
  const riskChart = useRef<echarts.ECharts | null>(null);

  /**
   * 加载回测任务列表
   */
  const loadBacktestList = async () => {
    setLoading(true);
    try {
      const response = await backtestApi.getBacktestList();
      if (response.backtests && Array.isArray(response.backtests)) {
        setBacktestTasks(response.backtests);
        // 如果有回测任务，默认选中第一个
        if (response.backtests.length > 0 && !selectedTaskId) {
          selectTask(response.backtests[0].id);
        }
      }
    } catch (error) {
      console.error('加载回测任务列表失败:', error);
    } finally {
      setLoading(false);
    }
  };

  /**
   * 加载回测结果详情
   * @param taskId 任务ID
   */
  const loadBacktestDetail = async (taskId: string) => {
    setLoading(true);
    try {
      const response = await backtestApi.getBacktestDetail(taskId);
      if (response && response.status === 'success') {
        setBacktestResult(response);
        setTrades(response.trades || []);
        setMetrics(response.metrics || []);
        // 更新收益率曲线和风险分析图表
        updateReturnChart(response.equity_curve);
        updateRiskChart(response.metrics);
      }
    } catch (error) {
      console.error('加载回测结果详情失败:', error);
    } finally {
      setLoading(false);
    }
  };

  /**
   * 选择回测任务
   * @param taskId 任务ID
   */
  const selectTask = (taskId: string) => {
    setSelectedTaskId(taskId);
    loadBacktestDetail(taskId);
  };

  /**
   * 更新收益率曲线图表
   */
  const updateReturnChart = (equityCurve: any[]) => {
    if (!returnChart.current || !equityCurve || equityCurve.length === 0) return;
    
    // 准备图表数据
    const dates = equityCurve.map(item => {
      if (typeof item.datetime === 'string') {
        return item.datetime;
      } else if (typeof item.Open_time === 'string') {
        return item.Open_time;
      }
      return '';
    }).filter(date => date !== '');
    
    const equity = equityCurve.map(item => item.Equity || 0);
    
    const option = {
      title: {
        text: '收益率曲线',
        left: 'center',
        textStyle: {
          fontSize: 16,
          fontWeight: 'normal'
        }
      },
      tooltip: {
        trigger: 'axis',
        formatter: '{b}: {c}'
      },
      xAxis: {
        type: 'category',
        data: dates
      },
      yAxis: {
        type: 'value'
      },
      series: [{
        data: equity,
        type: 'line',
        smooth: true,
        lineStyle: {
          color: '#4a6cf7'
        },
        areaStyle: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
            { offset: 0, color: 'rgba(74, 108, 247, 0.3)' },
            { offset: 1, color: 'rgba(74, 108, 247, 0.05)' }
          ])
        }
      }]
    };
    
    returnChart.current.setOption(option);
  };

  /**
   * 更新风险分析图表
   */
  const updateRiskChart = (metrics: MetricItem[]) => {
    if (!riskChartRef.current || !metrics || metrics.length === 0) return;
    
    // 查找最大回撤指标
    const maxDrawdownMetric = metrics.find(metric => metric.cn_name === '最大回撤');
    const maxDrawdown = maxDrawdownMetric ? maxDrawdownMetric.value : 0;
    
    const option = {
      title: {
        text: '最大回撤',
        left: 'center',
        textStyle: {
          fontSize: 14,
          fontWeight: 'normal'
        }
      },
      tooltip: {
        trigger: 'axis',
        formatter: '{b}: {c}%'
      },
      xAxis: {
        type: 'category',
        data: ['最大回撤']
      },
      yAxis: {
        type: 'value',
        axisLabel: {
          formatter: '{value}%'
        }
      },
      series: [{
        data: [maxDrawdown],
        type: 'bar',
        itemStyle: {
          color: '#f87272'
        }
      }]
    };
    
    riskChart.current?.setOption(option);
  };

  /**
   * 初始化收益率曲线图表
   */
  const initReturnChart = () => {
    if (!returnChartRef.current) return;
    
    returnChart.current = echarts.init(returnChartRef.current);
    
    const option = {
      title: {
        text: '收益率曲线',
        left: 'center',
        textStyle: {
          fontSize: 16,
          fontWeight: 'normal'
        }
      },
      tooltip: {
        trigger: 'axis',
        formatter: '{b}: {c}%'
      },
      xAxis: {
        type: 'category',
        data: []
      },
      yAxis: {
        type: 'value'
      },
      series: [{
        data: [],
        type: 'line',
        smooth: true,
        lineStyle: {
          color: '#4a6cf7'
        },
        areaStyle: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
            { offset: 0, color: 'rgba(74, 108, 247, 0.3)' },
            { offset: 1, color: 'rgba(74, 108, 247, 0.05)' }
          ])
        }
      }]
    };
    
    returnChart.current.setOption(option);
  };

  /**
   * 初始化风险分析图表
   */
  const initRiskChart = () => {
    if (!riskChartRef.current) return;
    
    riskChart.current = echarts.init(riskChartRef.current);
    
    const option = {
      title: {
        text: '最大回撤',
        left: 'center',
        textStyle: {
          fontSize: 14,
          fontWeight: 'normal'
        }
      },
      tooltip: {
        trigger: 'axis',
        formatter: '{b}: {c}%'
      },
      xAxis: {
        type: 'category',
        data: ['最大回撤']
      },
      yAxis: {
        type: 'value',
        axisLabel: {
          formatter: '{value}%'
        }
      },
      series: [{
        data: [0],
        type: 'bar',
        itemStyle: {
          color: '#f87272'
        }
      }]
    };
    
    riskChart.current.setOption(option);
  };

  /**
   * 监听窗口大小变化，调整图表大小
   */
  const handleResize = () => {
    returnChart.current?.resize();
    riskChart.current?.resize();
  };

  // 组件挂载时初始化图表和加载数据
  useEffect(() => {
    initReturnChart();
    initRiskChart();
    loadBacktestList();
    window.addEventListener('resize', handleResize);

    // 组件卸载时清理
    return () => {
      window.removeEventListener('resize', handleResize);
      returnChart.current?.dispose();
      riskChart.current?.dispose();
    };
  }, []);

  // 选中任务变化时加载详情
  useEffect(() => {
    if (selectedTaskId) {
      loadBacktestDetail(selectedTaskId);
    }
  }, [selectedTaskId]);

  /**
   * 获取关键指标
   * @returns 关键指标列表
   */
  const getKeyMetrics = () => {
    if (!metrics || metrics.length === 0) {
      return [];
    }
    
    // 提取关键指标
    const keyMetricNames = [
      '总收益率', '年化收益率', '最大回撤', '夏普比率', '胜率', '交易次数'
    ];
    
    return metrics.filter(metric => keyMetricNames.includes(metric.cn_name));
  };

  /**
   * 删除回测结果
   * @param taskId 任务ID
   */
  const deleteBacktest = async (taskId: string) => {
    try {
      await backtestApi.deleteBacktest(taskId);
      // 重新加载回测任务列表
      loadBacktestList();
      // 如果删除的是当前选中的任务，清空选中状态
      if (selectedTaskId === taskId) {
        setSelectedTaskId('');
        setBacktestResult(null);
        setTrades([]);
        setMetrics([]);
      }
    } catch (error) {
      console.error('删除回测结果失败:', error);
    }
  };

  return (
    <div className="backtest-results-container">
      <h1>{t('strategy_backtest')}</h1>
      
      <div className="backtest-layout">
        {/* 左侧：回测任务列表 */}
        <div className="backtest-list">
          <div className="panel">
            <div className="panel-header">
              <h2>回测任务</h2>
              <button className="btn btn-primary btn-sm">新建回测</button>
            </div>
            <div className="panel-body">
              {loading ? (
                <div className="loading">加载中...</div>
              ) : backtestTasks.length === 0 ? (
                <div className="empty">暂无回测任务</div>
              ) : (
                backtestTasks.map(task => (
                  <div 
                    key={task.id}
                    className={`backtest-task-item ${selectedTaskId === task.id ? 'active' : ''}`}
                    onClick={() => selectTask(task.id)}
                  >
                    <div className="task-header">
                      <div className="task-name">{task.strategy_name}</div>
                      <div className={`task-status ${task.status}`}>{task.status}</div>
                    </div>
                    <div className="task-meta">
                      <div className="task-date">{task.created_at}</div>
                      <div className="task-return">
                        {task.total_return !== undefined ? `${task.total_return}%` : 'N/A'}
                      </div>
                    </div>
                    <div className="task-actions">
                      <button 
                        className="btn btn-danger btn-xs"
                        onClick={(e) => {
                          e.stopPropagation();
                          deleteBacktest(task.id);
                        }}
                      >
                        删除
                      </button>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
        
        {/* 右侧：回测结果详情 */}
        <div className="backtest-detail">
          {selectedTaskId && backtestResult ? (
            <>
              {/* 回测概览 */}
              <div className="panel">
                <div className="panel-header">
                  <h2>回测概览</h2>
                </div>
                <div className="panel-body">
                  <div className="overview-grid">
                    {getKeyMetrics().map((metric, index) => (
                      <div key={index} className="metric-card">
                        <div className="metric-label">{metric.cn_name}</div>
                        <div className={`metric-value ${metric.name === 'Return [%]' && Number(metric.value) >= 0 ? 'positive' : ''} ${metric.name === 'Return [%]' && Number(metric.value) < 0 ? 'negative' : ''}`}>
                          {typeof metric.value === 'number' ? `${metric.value}%` : metric.value}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              
              {/* 绩效分析 */}
              <div className="panel">
                <div className="panel-header">
                  <h2>绩效分析</h2>
                </div>
                <div className="panel-body">
                  <div className="chart-container">
                    <div ref={returnChartRef} className="chart"></div>
                  </div>
                </div>
              </div>
              
              {/* 交易详情和风险分析 */}
              <div className="grid-layout">
                {/* 交易详情 */}
                <div className="panel">
                  <div className="panel-header">
                    <h2>交易详情</h2>
                  </div>
                  <div className="panel-body">
                    <div className="table-container">
                      <table className="data-table">
                        <thead>
                          <tr>
                            <th>入场时间</th>
                            <th>出场时间</th>
                            <th>方向</th>
                            <th>入场价格</th>
                            <th>出场价格</th>
                            <th>仓位大小</th>
                            <th>收益</th>
                            <th>收益率</th>
                          </tr>
                        </thead>
                        <tbody>
                          {trades.length === 0 ? (
                            <tr>
                              <td colSpan={8} className="empty">暂无交易记录</td>
                            </tr>
                          ) : (
                            trades.map((trade, index) => (
                              <tr key={index}>
                                <td>{trade.EntryTime}</td>
                                <td>{trade.ExitTime}</td>
                                <td>{trade.Direction}</td>
                                <td>{trade.EntryPrice}</td>
                                <td>{trade.ExitPrice}</td>
                                <td>{trade.Size}</td>
                                <td className={trade.PnL >= 0 ? 'positive' : 'negative'}>
                                  {trade.PnL >= 0 ? '+' : ''}{trade.PnL}
                                </td>
                                <td className={trade.ReturnPct >= 0 ? 'positive' : 'negative'}>
                                  {trade.ReturnPct >= 0 ? '+' : ''}{trade.ReturnPct}%
                                </td>
                              </tr>
                            ))
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                
                {/* 风险分析 */}
                <div className="panel">
                  <div className="panel-header">
                    <h2>风险分析</h2>
                  </div>
                  <div className="panel-body">
                    <div className="risk-metrics">
                      {metrics.filter(metric => ['波动率', '索提诺比率', '卡尔马比率', '信息比率'].includes(metric.cn_name)).map((metric, index) => (
                        <div key={index} className="risk-item">
                          <div className="risk-label">{metric.cn_name}</div>
                          <div className="risk-value">{metric.value}</div>
                        </div>
                      ))}
                    </div>
                    <div className="chart-container small">
                      <div ref={riskChartRef} className="chart"></div>
                    </div>
                  </div>
                </div>
              </div>
            </>
          ) : (
            <div className="empty-detail">
              {loading ? (
                <div className="loading">加载中...</div>
              ) : (
                <div className="empty">请选择一个回测任务查看详情</div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default BacktestResults;
